---
- name: Afficher la famille du système d'exploitation et la version majeure
  debug:
    msg: "ansible_os_family: {{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}"

- name: Inclure les tâches spécifiques pour les versions majeures de Debian
  include_tasks: "setup-Debian-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == "Debian"

- name: Inclure les tâches spécifiques pour les versions majeures d'Alpine
  include_tasks: "setup-Alpine-{{ ansible_distribution_version.split('.')[:2] | join('.') }}.yml"
  when: ansible_distribution == "Alpine"

- name: Inclure les tâches spécifiques pour les versions majeures de RockyLinux
  include_tasks: "setup-RockyLinux-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == "Rocky"