---
# tasks file for my-tools
- name: Installation des PAQUETS mc, tree, net-tools, htop, neofetch, wget, ufw
  apt:
    pkg: [mc, tree, net-tools, htop, neofetch, wget, ufw]
    update_cache: yes
    state: latest
