---
- name: Installation des PAQUETS
  ansible.builtin.apt:
    name: [mc, tree, net-tools, btop, neofetch, wget, ufw, ncdu, nmap, nano]
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian"