---
- name: Installation des PAQUETS
  community.general.apk:
    name: [mc, tree, net-tools, btop, neofetch, wget, ufw, ncdu, nmap, nano]
    state: latest
    update_cache: true
  when: ansible_distribution == "Alpine"