---
# tasks file for iscdhcp-debian
# Installation du paquets isc-dhcp-server
- name: Installation du PAQUETS isc-dhcp-server
  apt: pkg=isc-dhcp-server update_cache=yes state=latest

# Configuration de l'interface
- name: Configuration de l'interface eth0
  template: src=./templates/etc.network.interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode='0644'

# Redémarrage du services dhcpd
- name: Activation & Redémarrage du services isc-dhcp-server
  systemd: state=restarted name=networking enabled=yes masked=no

# Configuration de iscdhcp
- name: Configuration du dhcp
  template: src=./templates/etc.dhcp.dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode='0644'

# Redémarrage du services dhcpd
- name: Activation & Redémarrage du services isc-dhcp-server
  systemd: state=restarted name=isc-dhcp-server enabled=yes masked=no
